-define(Makefile,
    "PROJECT = erlang~n"
    "~n"
    "PREFIX = usr/local~n"
    "~n"
    "BIN_DIR = bin~n"
    "LIB_DIR = lib~n"
    "~n"
    "BIN_PATH = $(DEST_DIR)/$(PREFIX)/$(BIN_DIR)~n"
    "LIB_PATH = $(DEST_DIR)/$(PREFIX)/$(LIB_DIR)/$(PROJECT)~n"
    "~n"
    "ERTS_BIN = $(shell ls -d erts-*)/bin~n"
    "BINARIES = ct_run dialyzer epmd erl erlc escript run_erl to_erl typer~n"
    "~n"
    "usage:~n"
    "	@echo \"Usage: make install|uninstall\"~n"
    "~n"
    "install:~n"
    "	find . -type d -exec mkdir -p \"$(LIB_PATH)/{}\" \\;~n"
    "	find $(ERTS_BIN) -type f -exec install -m 555 \"{}\" \"$(LIB_PATH)/{}\" \\;~n"
    "	find lib -type f -exec install -m 444 \"{}\" \"$(LIB_PATH)/{}\" \\;~n"
    "	find bin -type f -exec install -m 644 \"{}\" \"$(LIB_PATH)/{}\" \\;~n"
    "	mkdir -p $(BIN_PATH)~n"
    "	$(foreach binary,$(BINARIES),\\~n"
    "		ln -s ../$(LIB_DIR)/$(PROJECT)/$(ERTS_BIN)/$(binary) $(BIN_PATH)/;)~n"
    "	sed -i \"\" 's/\\(ROOTDIR=\\).*/\\1\"\\/$(PREFIX)\\/$(LIB_DIR)\\/$(PROJECT)\"/' \\~n"
    "		$(LIB_PATH)/$(ERTS_BIN)/erl~n"
    "~n"
    "uninstall:~n"
    "	$(foreach binary,$(BINARIES),rm $(BIN_PATH)/$(binary);)~n"
    "	rmdir -p $(BIN_PATH) 2>/dev/null || true~n"
    "	find bin -type f -exec rm -f \"$(LIB_PATH)/{}\" \\;~n"
    "	find lib -type f -exec rm -f \"$(LIB_PATH)/{}\" \\;~n"
    "	find $(ERTS_BIN) -type f -exec rm -f \"$(LIB_PATH)/{}\" \\;~n"
    "	find . -type d -exec rmdir -p \"$(LIB_PATH)/{}\" 2>/dev/null \\;~n"
    "	rmdir -p $(LIB_PATH) 2>/dev/null || true~n"
).
